from gringotts.waiter.plugins import floatingip
from gringotts.waiter.plugins import image
from gringotts.waiter.plugins import instance
from gringotts.waiter.plugins import router
from gringotts.waiter.plugins import snapshot
from gringotts.waiter.plugins import user
from gringotts.waiter.plugins import volume
from gringotts.waiter.plugins import alarm
from gringotts.waiter.plugins import listener
from gringotts.waiter.plugins import share
